export const userDetails = [
  {
    id: 1,
    fname: "Bipul",
    lname: "Singh",
    dob: "1999-2-17",
    age: 23,
    password: "1234",
    email: "bipul@gmail.com",
  },
  {
    id: 2,
    fname: "Yaswardhan",
    lname: "Jaiswal",
    dob: "1999-2-17",
    age: 27,
    password: "1234",
    email: "yash@gmail.com",
  },
  {
    id: 3,
    fname: "Pavan",
    lname: "Patil",
    dob: "1999-2-20",
    age: 25,
    password: "1234",
    email: "pavan@gmail.com",
  },
  {
    id: 4,
    fname: "Harshad",
    lname: "Kajale",
    dob: "1999-2-18",
    age: 40,
    password: "1234",
    email: "hashad@gmail.com",
  },
  {
    id: 5,
    fname: "Virender",
    lname: "Nath",
    dob: "1999-2-18",
    age: 32,
    password: "1234",
    email: "virendra@gmail.com",
  },
  {
    id: 6,
    fname: "Rahul",
    lname: "Kumar",
    dob: "1999-2-19",
    age: 22,
    password: "1234",
    email: "rahul@gmail.com",
  },
];
